export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_FRISCH_PENDING = 'REQUEST_FRISCH_PENDING';
export const REQUEST_FRISCH_SUCCESS = 'REQUEST_FRISCH_SUCCESS';
export const REQUEST_FRISCH_FAILED = 'REQUEST_FRISCH_FAILED'